version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://username:password@db:5432/yourdb
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yourdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
